### ISSUE TITLE
TypeError: methodFn is not a function

### ISSUE THREAD

**Issue by AnYiEE** [DawidWraga/davstack#8]
Hello, when I was developing a React application using Next.js, an error occurred on the page:

```
Unhandled Runtime Error
TypeError: methodFn is not a function

Object.apply  
 node_modules\.pnpm\@davstack+store@1.4.2_@types+react@18.3.3_react@18.3.1\node_modules\@davstack\store\dist\index.mjs (338:1)
```
This happened at [this line](https://github.com/DawidWraga/davstack/blob/main/packages/store/src/create-state-methods/create-methods-proxy.ts#L74), but the actual functionality is working fine. Why did this happen? Can we add a relevant check before calling `methodFn`?

**Comment by AnYiEE** [comment]
I changed `methodFn(...args);` to `methodFn?.(...args);` and got a new error: the first one is `Method yyy not found`, followed by `Method xxx not found`, but I am indeed calling store.xxx.yyy.set to update the state. Although I don't know why, everything else is normal besides the error in the console, and the state can still be updated normally.

**Comment by DawidWraga** [comment]
Hey I believe this is likely due to the fact that the get/set/use/assign methods are generated lazily for performance reasons 

For example

This won't work because set is not actually defined

onValueChange={textInputStore.set}

This will work

onValueChange={(v)=>textInputStore.set(v)}

Let me know if that helps and I'll add this to the docs

**Comment by AnYiEE** [comment]
I did as you said, but it seems to have no effect.

I am using the `Autocomplete` component of NextUI, passing the set method to both `onInputChange` and `onSelectionChange` props. As you said, I changed [this line](https://github.com/AnYiEE/touhou-mystia-izakaya-assistant/blob/master/app/components/sideSearchIconButton.tsx#L51) to `onInputChange={(value) => {setSearchValue(value)}}`, but still getting the same error here, while there is no issue with onSelectionChange below. It throws an error, but the value is still correctly updated.

The stack trace is as follows (although posting it may not be useful).

```
index.mjs:355 Uncaught TypeError: methodFn is not a function
    at Object.apply (index.mjs:355:16)
    at onInputChange (VM3401 sideSearchIconButton.tsx:52:25)
    at onChangeCaller (useControlledState.mjs:34:54)
    at eval (useControlledState.mjs:59:13)
    at resetInputValue (useComboBoxState.mjs:136:9)
    at commitSelection (useComboBoxState.mjs:214:13)
    at Object.commitValue [as close] (useComboBoxState.mjs:223:39)
    at eval (chunk-3EZFM4QW.mjs:179:15)
    at onPress (chunk-3EZFM4QW.mjs:218:21)
    at eval (usePress.mjs:133:13)
    at eval (useEffectEvent.mjs:32:54)
    at HTMLDocument.onPointerUp (usePress.mjs:318:107)
```

**Comment by DawidWraga** [comment]
Hey I'm sorry I didn't get back to you on this sooner. 

I think I may have figured out the cause of your bug.

There are certain keywords that cannot be used because of how some of the store is implemented.

In particular, I believe that if you use the words `options`, `input`, `output`, `computed`, `effects` as a key in your store then it will cause the store to throw an error when you call get/set/use

for example
using `store( { options: [...] } )` will not work
but using `store( { opts: [...] } )` will work fine

Let me know if this fixed your issue and I'll document this better.

Thanks for your understanding and I welcome any additional feedback!

**Comment by AnYiEE** [comment]
> I believe that if you use the words `options`, `input`, `output`, `computed`, `effects` as a key

When I first started using it, I did use `state` as a key, which caused issues and was quickly changed. I don't think I have that anymore now. If you have time, you can [take a quick look](https://github.com/AnYiEE/touhou-mystia-izakaya-assistant/blob/master/app/stores/customer-rare.ts#L38) at how I'm using it. Thank you.
